name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        with:
          bun-version: latest

      - name: Run build
        run: bun run build

      - name: remove unused files
        run: rm -rf resources/js resources/css .github tests node_modules phpunit.xml tsconfig.json package-lock.json package.json bun.lock composer.lock .gitattributes .editorconfig README.md vite.config.js .env.example

      - name: Commit and push build files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f .
          git commit -m "Add build files" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:build -f